import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio App Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen min-h-screen bg-gradient-to-b from-blue-100 to-red-100">
          <div className="h-24">
            <Navbar />
          </div>
          
          {/* CHANGED THE H-[CALC(100VH-6REM)] TO FLEX-GROW */}
          <div className="flex-grow ">{children}</div>
        </div>
        
        </body>
    </html>
  );
}
